# ==============================================================================
# Alacritty Configuration File
# Сгенерировано на основе ваших настроек терминала.
# ==============================================================================

# ------------------------------------------------------------------------------
# Shell (Оболочка)
# ------------------------------------------------------------------------------
# Программа, которая будет запускаться в терминале.
# Оставьте по умолчанию, если не знаете, какую оболочку используете.
[shell]
program = "/usr/bin/zsh" # Или "/usr/bin/zsh", "/usr/bin/fish"
args = ["--login"]

# ------------------------------------------------------------------------------
# Font (Шрифт)
# ------------------------------------------------------------------------------
# Настройки шрифта.
# Из ваших скриншотов: FiraCode Nerd Font, размер 14.
[font]
size = 16.0 # Размер шрифта в пунктах.

[font.normal]
family = "FiraCode Nerd Font" # Название шрифта для обычного текста
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font" # Название шрифта для жирного текста
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font" # Название шрифта для курсива
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font" # Название шрифта для жирного курсива
style = "Bold Italic"

# ------------------------------------------------------------------------------
# Colors (Цветовая схема)
# ------------------------------------------------------------------------------
# Настройки цветов.
# Основано на вашей палитре, используются стандартные цвета Alacritty для похожих оттенков.
[colors.primary]
foreground = "#ABB2BF" # Цвет текста (светло-серый, похож на белый)
#background = "#282C34" # Цвет фона (темно-серый, похож на темно-синий/черный)
background = "#242424" # Цвет фона (темно-серый, похож на темно-синий/черный)

[colors.cursor]
text = "CellBackground" # Цвет текста под курсором
cursor = "#56B6C2"     # Цвет самого курсора (бирюзовый, для примера)

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "#E5C07B"

[colors.selection]
text = "CellForeground"
background = "#3E4452" # Цвет выделенного текста

# Standard colors (ANSI 0-7)
[colors.normal]
black   = "#1E2127" # Темно-серый
red     = "#E06C75" # Красный
green   = "#98C379" # Зеленый
yellow  = "#418db0" # Желтый
blue    = "#6ba0b9" # Синий
magenta = "#C678DD" # Пурпурный
cyan    = "#56B6C2" # Голубой
white   = "#ABB2BF" # Светло-серый

# Bright colors (ANSI 8-15)
[colors.bright]
black   = "#5C6370" # Светло-серый
red     = "#E06C75" # Красный
green   = "#98C379" # Зеленый
yellow  = "#418db0" # Желтый
blue    = "#bfe6fb" # Синий
magenta = "#C678DD" # Пурпурный
cyan    = "#56B6C2" # Голубой
white   = "#FFFFFF" # Белый

# ------------------------------------------------------------------------------
# Window (Окно)
# ------------------------------------------------------------------------------
# Настройки внешнего вида окна терминала.
# Из ваших скриншотов: 80 столбцов, 24 ряда.
[window]
dimensions = { columns = 100, lines = 30 } # Начальный размер окна в символах.
padding = { x = 10, y = 10 }               # Отступы от края окна до текста.
opacity = 0.95                             # Прозрачность окна (0.0 - полностью прозрачно, 1.0 - полностью непрозрачно).
decorations = "none"                       # Декорации окна: "full", "none", "buttonless".
startup_mode = "Windowed"                  # Режим запуска: "Windowed", "Fullscreen", "Maximized".
dynamic_padding = true                     # Автоматически центрировать текст в окне.

# ------------------------------------------------------------------------------
# Cursor (Курсор)
# ------------------------------------------------------------------------------
# Настройки курсора.
# Из ваших скриншотов: Форма курсора "Блок", мигание "По умолчанию" (Off).
[cursor]
style = { shape = "Block", blinking = "Off" } # Форма курсора: "Block", "Underline", "Beam". Мигание: "On", "Off", "Sense".
thickness = 0.15 # Толщина курсора (для "Underline" или "Beam").

# ------------------------------------------------------------------------------
# Scrolling (Прокрутка)
# ------------------------------------------------------------------------------
# Настройки прокрутки.
# Из ваших скриншотов: 10000 линий прокрутки.
[scrolling]
history = 10000 # Количество строк в буфере прокрутки.

# ------------------------------------------------------------------------------
# Key Bindings (Горячие клавиши)
# ------------------------------------------------------------------------------
# Пользовательские горячие клавиши.
# 'mods': Control, Shift, Alt, Super (клавиша Windows/Command)
# 'action': Copy, Paste, IncreaseFontSize, DecreaseFontSize, ResetFontSize и т.д.
#
# Важно: для каждой привязки клавиш используйте [[keyboard.bindings]]
#
[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"

# Раскомментируйте эти строки, если вам нужны стандартные копирование/вставка
[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"
#
[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"
